name: Adobe Guides
favicon: null
layout_spectrum: 0.8453646588604897
typography_spectrum: 0.1475999872200191
title: Adobe Guides
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2988308204803616
  lightness: 0.5274913706816733
  saturation: 0.7450797101482749
  rhythmicContrast: 0.8369634752161801
purpose: []
